### ISSUE TITLE
Firmwareversion?

### ISSUE THREAD

**Issue by Tibercad** [MAVProxyUser/CIAJeepDoors#16]
Hi,

does this tool need a specific version of firmware or will it work with the latest one?

I'm only getting my Mavic 2 Pro tonight and wanted to make sure it wasn't sending any real data to anyone else.

**Comment by MAVProxyUser** [comment]
We do not have a list of known good firmware. 

So your answer is "yes". 

https://github.com/MAVProxyUser/CIAJeepDoors/issues/1

**Comment by xsszw** [comment]
mavic 2  pro 01.00.0770  The hack is work but is reset after no time after I turned on the Smartcontroller then everything off again and the drone turned on again and the ID was there again hmm

**Comment by MAVProxyUser** [comment]
https://github.com/MAVProxyUser/CIAJeepDoors/issues/1
