### ISSUE TITLE
not working with avata

### ISSUE THREAD

**Issue by asdrolf** [MAVProxyUser/CIAJeepDoors#17]
i am trying to disable id on dji avata. but i am not sure if am doing something wrong. it doesnt detect the drone.
it hangs here:
        ser = open_usb(po)

**Comment by asdrolf** [comment]
I'm trying to use it with Avata but in COM it doesnt detect the drone and in bulk mode it doesnt connect either. I installed libusb, should i create a device filter... not sure for what it is, i tried but now it freezes.

**Comment by MAVProxyUser** [comment]
New drone models do not work... period.
