### ISSUE TITLE
can only concatenate str (not nonetype ) to str

### ISSUE THREAD

**Issue by Sora177** [MAVProxyUser/CIAJeepDoors#18]
I'm really sorry if I'm not supposed to post this here but I'm not sure where else I would ask for help. Whenever I select my drone in the COM-PORT and click connect drone I first get a message that says "No response received" If I then continue and select Connect drone it then says "can only concatenate str (not nonetype ) to str" I tried asking in a Python Discord server about this but was told to ask here since they believe it's against ToS and didn't want to help because of that. 

Thank you and I really appreciate any help I can get on this! 
![image](https://user-images.githubusercontent.com/107719846/199056953-7e6aee31-686b-4fe5-b3da-b3a12a824b7f.png)

**Comment by Sora177** [comment]
I trield running it as a PY file and was told it's given me a different error would anyone know what this is? 

![image](https://user-images.githubusercontent.com/107719846/199309067-c0c1be73-19a4-4cb6-96fb-cee9d4e6d56a.png)

**Comment by MAVProxyUser** [comment]
windows is gross.... try linux

**Comment by Sora177** [comment]
Managed to get it working. You have to be on the latest update if you are using the DJI Mavic Pro
