### ISSUE TITLE
DJI Avata Unable to connect

### ISSUE THREAD

**Issue by igorwojda** [MAVProxyUser/CIAJeepDoors#19]
DJI Assistant (Consumer Series 2) detects the drone correctly, 

CIA Jeep Doors App UI:
`No device connected or the device did not answer`

Console displays (connecting in `Bulk`):
```
No response received
cannot unpack non-iterable NoteType object
```

`Com-port` connection does not has any items on the list

Version: CIA Jeep Doors Gui v1.3 
OS Win 10
DJI Assistant (Consumer Series 2) v2.1.13

**Comment by MAVProxyUser** [comment]
New DJI drones are not supported.
