### ISSUE TITLE
Still visible by AS?

### ISSUE THREAD

**Issue by Newegz** [MAVProxyUser/CIAJeepDoors#4]
![P4register](https://user-images.githubusercontent.com/106453438/171744910-510af39a-c7b2-42dd-bf7a-cd4fc5b1759d.JPG)
Hi. I applied the code to P4 (WM 330 V02.00.0700). Here is how it is seen by mobile AeroScope. Certainly something is going on there, since at first the drone was not located, but after 15s or so - coordinates and SN were identified. From that point it was on/off situation. The drone was sitting on the ground and not flying. Any idea why it did not work for this P4?

**Comment by MAVProxyUser** [comment]
Please see the advice here. 
https://github.com/MAVProxyUser/CIAJeepDoors/issues/1
Someone needs to actually patch the FC firmware... or root and keep sending DUML. exercise for the reader.
