### ISSUE TITLE
DJI fly apk - reactivation AS under certain circumstances

### ISSUE THREAD

**Issue by edyno** [MAVProxyUser/CIAJeepDoors#6]
Aeroscope :: Be careful with the DJI fly app on Android. I found that after deactivating the AS.
The apk DJI fly reactivates it after switching to the "Menu >> Safety >> Aeroscope" page. 
(it is not necessary to change any parameter on this tab)
Change status from [00] to [5f] or even [ff].

[Tested with command:: comm_serialtalk.py comxy -a 2 -t 1000 -r 0300 -s 3 -i 218 -x 06]

After deactivation of AS, the output is follows::
55 13 04 03 03 0a 00 00 80 03 da 06 00 00 00 00 00 8d 1f

After opening the aeroscope tab on DJI fly apk [android]::
55 13 04 03 03 0a 00 00 80 03 da 06 00 5f 00 00 00 62 78
or::
55 13 04 03 03 0a 00 00 80 03 da 06 00 ff 00 00 00 5f da

Aircraft:        Mini 2
Aircraft firmware:      01.03.0000
RC firmware:          02.00.1101
apk version:          1.4.2

**Comment by MAVProxyUser** [comment]
Please see: https://github.com/MAVProxyUser/CIAJeepDoors/issues/1
