### ISSUE TITLE
How To Upload Firmware To Drone

### ISSUE THREAD

**Issue by cplaks** [MAVProxyUser/CIAJeepDoors#7]
Hi all,
Probably a very dumb question but I am new to drones. I have the CIAJeepDoors.py downloaded and moved into the dji-firmware-tools-master folder. However, how do I actually run the hack so that the firmware updates on my drone? I have a Maverick mini and I usb connect it to my computer.

Thanks,
Connor

**Comment by KonradIT** [comment]
https://github.com/MAVProxyUser/CIAJeepDoors#tldr-how-do-i-use-this=

**Comment by cplaks** [comment]
I see the command but trying to run that in the windows 10 command prompt does nothing.... I'm trying to figure out how to use it.

**Comment by MAVProxyUser** [comment]
there used to be a #spoonfeeding channel on the Mattermost / Slack for "OG's" but most will encourage you to do some more homework. You may not be the target audience for this tool.
