### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by psxbxr** [MAVProxyUser/CIAJeepDoors#8]
Using Python 3.10.06 with dev-tools. Can't get past the type error.

```
C:\dji-firmware-tools-master> python.exe .\CIAJeepDoors.py --port COM3
CIA Jeep Doors
DJI DroneID adjustment tool v1.2
======================================
this software is based on the work of the DJI OG's
it is free software and should never be sold
======================================
greetings from Bin4ry
Traceback (most recent call last):
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 226, in <module>
    print_droneid_state(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 161, in print_droneid_state
    state = get_privacy(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 132, in get_privacy
    pkt, payload = send_duml_receive_reply(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 30, in send_duml_receive_reply
    return pktrpl, pktrpl[11:-2]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by MAVProxyUser** [comment]
https://github.com/MAVProxyUser/CIAJeepDoors/issues/1

This flat out does not work on some firmware versions.

**Comment by psxbxr** [comment]
Bummer, guess it doesn't work for Mavic Pro Platinum V01.04.0300

I still had success with DUMLRacer and the deejayeye modder. 
Thank you for putting this out regardless.

**Comment by MAVProxyUser** [comment]
V01.04.0300 is old AF, I'd imagine it should work fine there.

**Comment by MAVProxyUser** [comment]
Stop using windows. ;) 
Try the alternate USB dll. 
https://github.com/MAVProxyUser/CIAJeepDoors/blob/main/CIAJeepdoors_1.2/libusb0.dll

**Comment by MAVProxyUser** [comment]
https://www.youtube.com/watch?v=Nmrn6EIOC-Q

**Comment by psxbxr** [comment]
That's what I thought. It's the FW that allowed more parameters/restrictions to be changed. How should I be using the DLL? I tried replacing it with the one in System32, no luck. Do you have a source for the *.inf file for that version? I could update/change through device manager with it. 

digdat0's video on it is how I came across the tool lol.

Thanks again!

**Comment by psxbxr** [comment]
Holy sht.. It was a corrupt FW. Reflashed and profit. Both versions worked. Above and beyond with the new GUI. digdat0 even did an update video on it lol. Thank you!
