### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by Ottoissblato** [MAVProxyUser/CIAJeepDoors#9]
Came across this error in cmd on initial try.  Not sure how to get past it.

Traceback (most recent call last):
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by dereksynkopa** [comment]
I have the same problem on two computers. I tried to run the command> python comm_mkdupc.py -h and this command responded correctly. I think there is a problem inside CIAJeepDoors.py.

**Comment by psxbxr** [comment]
I think you need the library.

`python -m pip install python-dev-tools`


 I ran into that problem at first, but now I have that TypeError I opened an issue for.

```
C:\dji-firmware-tools-master> python.exe .\CIAJeepDoors.py --port COM3
CIA Jeep Doors
DJI DroneID adjustment tool v1.2
======================================
this software is based on the work of the DJI OG's
it is free software and should never be sold
======================================
greetings from Bin4ry
Traceback (most recent call last):
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 226, in <module>
    print_droneid_state(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 161, in print_droneid_state
    state = get_privacy(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 132, in get_privacy
    pkt, payload = send_duml_receive_reply(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 30, in send_duml_receive_reply
    return pktrpl, pktrpl[11:-2]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dereksynkopa** [comment]
exactly! I used the commands:
python -m pip install requests, then python -m pip install requests
and it worked.

**Comment by psxbxr** [comment]
You get a droneid status return and all? I can't figure this type error..

**Comment by dereksynkopa** [comment]
I was too happy too soon. Now I have this problem:
AttributeError: module 'serial' has no attribute 'Serial'

**Comment by psxbxr** [comment]
You're installing the different modules it's going to call for like I did. Get python-dev-tools. it'll install the prerequisite.

**Comment by dereksynkopa** [comment]
Installing libraries did not help, after restarting serial attribute error still. You must probably enter a value.

**Comment by psxbxr** [comment]
Testing older versions of python right now. Currently 3.9 from march release.

**Comment by psxbxr** [comment]
Getting that now..

```
Traceback (most recent call last):
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 221, in <module>
    ser = serial.Serial(po.port, baudrate=po.baudrate, timeout=0)
AttributeError: module 'serial' has no attribute 'Serial'
```

Starting to assume a line of code is missing or scrambled. (Censored)

**Comment by dereksynkopa** [comment]
I checked Python 3.9.11. The same problem.

**Comment by Ottoissblato** [comment]
@psxbxr  you were right, I needed to install dev tools.  I've done that now, then had errors for serial.  Installed that also, then it worked.  I'm now at the same serial attribute error.  oh the simple joys of getting one step ahead then smacking the wall. lol

Traceback (most recent call last):
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 221, in <module>
    ser = serial.Serial(po.port, baudrate=po.baudrate, timeout=0)
AttributeError: module 'serial' has no attribute 'Serial'

**Comment by psxbxr** [comment]
Even with the serial you also have to pip uninstall and install pyserial and add its' filepath to the system variable PATH. I'm back to the none type error.. Concluding there's an error in the code. 

```
PS C:\dji-firmware-tools-master> python CIAJeepDoors.py --port COM3
CIA Jeep Doors
DJI DroneID adjustment tool v1.2
======================================
this software is based on the work of the DJI OG's
it is free software and should never be sold
======================================
greetings from Bin4ry
Traceback (most recent call last):
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 226, in <module>
    print_droneid_state(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 161, in print_droneid_state
    state = get_privacy(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 132, in get_privacy
    pkt, payload = send_duml_receive_reply(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 30, in send_duml_receive_reply
    return pktrpl, pktrpl[11:-2]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Ottoissblato** [comment]
Got it. I tried unistall pyserial... and it reported not being installed.  I installed it and retried... now it's reading.  Droneid enabled is reported.

C:\dji-firmware-tools-master>python -m pip uninstall pyserial
WARNING: Skipping pyserial as it is not installed.

C:\dji-firmware-tools-master>python -m pip install pyserial
Collecting pyserial
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     ---------------------------------------- 90.6/90.6 kB 2.6 MB/s eta 0:00:00
Installing collected packages: pyserial
Successfully installed pyserial-3.5

[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\dji-firmware-tools-master>python CIAJeepDoors.py -d
CIA Jeep Doors
DJI DroneID adjustment tool v1.2
======================================
this software is based on the work of the DJI OG's
it is free software and should never be sold
======================================
greetings from Bin4ry
usage: CIAJeepDoors.py [-h] (--port PORT | --bulk) [-p PRIVACY] [-d DRONEID] [-f FLIGHTPURPOSE] [--disable] [--enable]
CIAJeepDoors.py: error: argument -d/--droneid: expected one argument

C:\dji-firmware-tools-master>python CIAJeepDoors.py --port com8 -d
CIA Jeep Doors
DJI DroneID adjustment tool v1.2
======================================
this software is based on the work of the DJI OG's
it is free software and should never be sold
======================================
greetings from Bin4ry
usage: CIAJeepDoors.py [-h] (--port PORT | --bulk) [-p PRIVACY] [-d DRONEID] [-f FLIGHTPURPOSE] [--disable] [--enable]
CIAJeepDoors.py: error: argument -d/--droneid: expected one argument

C:\dji-firmware-tools-master>python CIAJeepDoors.py --port com8
CIA Jeep Doors
DJI DroneID adjustment tool v1.2
======================================
this software is based on the work of the DJI OG's
it is free software and should never be sold
======================================
greetings from Bin4ry
=+=+=+=+=+=+=+=+=+=+=+=+
--> DroneID is enabled
=+=+=+=+=+=+=+=+=+=+=+=+

++++++++++++++++++++++++++++++++++++++
Please only use Android DJI Fly, the iOS version will reset the privacy bits.
++++++++++++++++++++++++++++++++++++++

**Comment by psxbxr** [comment]
@Ottoissblato fkyeah.  Going to reinstall the latest python again - try again.. lol

**Comment by Ottoissblato** [comment]
lol do it! btw sorry for the ridiculous font there.... dunno what happend but cmd blew it all up.

**Comment by Ottoissblato** [comment]
Does anyone have the info to use an SDR and repo to test this?  I could swear there was something out there where it would sort the blip and organize it into readable info.  This way we can see if the blip is officially turned off on the unit.  Thoughts?

**Comment by Ottoissblato** [comment]
Maybe even a mobile solution of this, as one person mentioned checking and/or setting it before each flight.

**Comment by dereksynkopa** [comment]
You need to install pyserial and it will be ok.

**Comment by psxbxr** [comment]
@Ottoissblato Don't know about the SDR test, but I read somewhere the DJI Go App might reset some flags on the drone if you open update the rules inside the app.

Reinstalled python 310. installed python-dev-tools, serial and pyserial.
Still with this type error.. Hoping someone can shed light on this.
```
PS C:\dji-firmware-tools-master> python .\CIAJeepDoors.py --port COM3
CIA Jeep Doors
DJI DroneID adjustment tool v1.2
======================================
this software is based on the work of the DJI OG's
it is free software and should never be sold
======================================
greetings from Bin4ry
Traceback (most recent call last):
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 226, in <module>
    print_droneid_state(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 161, in print_droneid_state
    state = get_privacy(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 132, in get_privacy
    pkt, payload = send_duml_receive_reply(po)
  File "C:\dji-firmware-tools-master\CIAJeepDoors.py", line 30, in send_duml_receive_reply
    return pktrpl, pktrpl[11:-2]
TypeError: 'NoneType' object is not subscriptable
```

Hope it's not my drone. I use the DJI USB Virtual COM drivers..

Were you able to disable anything successfully? Saw you had gotten the droneid status.

**Comment by dereksynkopa** [comment]
C:\DJI\dji-firmware-tools-master>python ciajeepdoors.py --port com6 --disable
CIA Jeep Doors
DJI DroneID adjustment tool v1.2
======================================
this software is based on the work of the DJI OG's
it is free software and should never be sold
======================================
greetings from Bin4ry
=+=+=+=+=+=+=+=+=+=+=+=+
--> DroneID is enabled
=+=+=+=+=+=+=+=+=+=+=+=+
--> Disabling DroneID
--> Done
=+=+=+=+=+=+=+=+=+=+=+=+
--> DroneID is disabled

**Comment by MAVProxyUser** [comment]
After installing python requests if this does not work then your firmware probably does not support it. 
https://github.com/MAVProxyUser/CIAJeepDoors/issues/1

You can use this repo for Occusync testing: 
https://github.com/proto17/dji_droneid

or Kismet for enhanced wifi testing.

**Comment by dereksynkopa** [comment]
I also checked that the mini 2 f.w. 1.3.0000 with DJIFly 1.6.10 DroneID will be turned on again.

**Comment by MAVProxyUser** [comment]
There are logical ways to fix that situation... exercise left to the reader.

**Comment by dereksynkopa** [comment]
I checked fpv raicer f.w.1.2.0000. The DroneID setting is permanently disabled. It follows that DjiFly resets the setting.

**Comment by MAVProxyUser** [comment]
soooo... don't allow DJIJFly to directly connect ;) proxy its DUML commands and filter some out... many ways to skin this cat

**Comment by MAVProxyUser** [comment]
use something like Friday to adjust DJIFLy's behavior...

**Comment by dereksynkopa** [comment]
I checked that all DJIfly versions from 1.6 upwards turn on DroneID even in airplane mode. Latest version 1.5.10 (1070) that does not turn on, even on-line. It would be good to know how to disable it in newer versions of DJI Fly.
